# Generated by Django 5.0.3 on 2024-04-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=15)),
                ('fundacion', models.DateField()),
                ('color_primario', models.CharField(max_length=7)),
                ('color_secundario', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'partidopolitico',
                'db_table_comment': 'Tabla para los partidos',
            },
        ),
        migrations.CreateModel(
            name='VotosPorAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('cantidad_votos', models.PositiveIntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakeit.partidopolitico')),
            ],
            options={
                'db_table': 'votosporanio',
                'db_table_comment': 'Tabla para los votos por partidos',
            },
        ),
    ]
